FROM ubuntu:18.04

RUN apt-get update -y && \
    apt-get install -y python3-pip python3-dev

#Run pip install --upgrade pip

#RUN mkdir api

COPY ./requirements.txt /api/requirements.txt
COPY ./api.py /api/api.py

WORKDIR /api

RUN pip3 install -r requirements.txt


EXPOSE 5000

# RUN ls

ENTRYPOINT ["python3"]

CMD ["api.py"]
